name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.11'

    - name: Azure Login
      uses: azure/login@v1.6.1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: terraform init -backend-config="client_id=${{ secrets.ARM_CLIENT_ID }}" -backend-config="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -backend-config="tenant_id=${{ secrets.ARM_TENANT_ID }}" -backend-config="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      working-directory: ./terraform

    - name: Force Unlock Terraform State
      run: terraform force-unlock 784aaf61-df49-dd22-ac27-d551e3168bbc
      working-directory: ./terraform
      
    - name: Terraform Apply
      run: terraform apply -auto-approve -var "client_id=${{ secrets.ARM_CLIENT_ID }}" -var "client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var "tenant_id=${{ secrets.ARM_TENANT_ID }}" -var "subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"
      working-directory: ./terraform
